language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

before_install:
- phpenv config-rm xdebug.ini

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit
