language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
- >
  echo;
  echo "Linting all PHP files";
  find config/ src/ tests/ -name ''*.php'' -print0 | xargs -0 -n 1 -P 4 php -l;

- >
  echo;
  echo "Running the unit tests";
  vendor/bin/phpunit tests/;
